name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build web release
        run: flutter build web --release
      - name: Build APK
        run: flutter build apk --release
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/web
            build/app/outputs/flutter-apk/app-release.apk

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS app
        run: flutter build macos
      - name: Archive macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-artifact
          path: build/macos/Build/Products/Release/*.app

  release:
    needs: [build, build_macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: actions/download-artifact@v4
        with:
          name: build-macos-artifact
      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/web/**
            build/app/outputs/flutter-apk/app-release.apk
            build/macos/Build/Products/Release/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
