name: Flutter CI/CD

on:
  push:
    branches: [ main, iosbuild ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build web release
        run: flutter build web --release
      - name: Build APK
        run: flutter build apk --release
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/web
            build/app/outputs/flutter-apk/app-release.apk

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS app
        run: flutter build macos
      - name: Archive macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-artifact
          path: build/macos/Build/Products/Release/*.app

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Clean build artifacts
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Precache iOS artifacts
        run: flutter precache --ios
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..
      - name: Ensure iOS plugin registrant is generated
        run: flutter pub get
      - name: Build iOS app
        run: flutter build ios --no-codesign
      - name: Archive iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-ios-artifact
          path: build/ios/iphoneos/*.app

  release:
    needs: [build, build_macos, build_ios]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: actions/download-artifact@v4
        with:
          name: build-macos-artifact
      - uses: actions/download-artifact@v4
        with:
          name: build-ios-artifact
      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/web/**
            build/app/outputs/flutter-apk/app-release.apk
            build/macos/Build/Products/Release/*.app
            build/ios/iphoneos/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
